version: '3.3'

services:
  application-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      GAME_SERVICE_URL: http://game-service:8081
      SESSION_SERVICE_URL: http://session-service:8084
      # TODO: add authentication service url
    ports:
      - 8080:8080
    networks:
      - game-network
      - appliction-network
      - session-network
    volumes:
      - maven_packages:/root/.m2

networks: 
  game-network:
    name: game-network
  appliction-network:
    name: appliction-network
  session-network:
    name: session-network

volumes:
  maven_packages:
    name: maven_packages