version: '3.3'

services:
  application_service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    networks:
      - game-network
      - appliction-network
    volumes:
      - maven_packages:/root/.m2

networks: 
  game-network:
    name: game-network
  appliction-network:
    name: appliction-network

volumes:
  maven_packages:
    name: maven_packages