version: '3.3'

services:
  application-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      GAME_SERVICE_URL: http://game-service:8081
      SESSION_SERVICE_URL: http://session-service:8084
      AUTHENTICATION_SERVICE_URL: http://authentication-service:8082
      JDBC_DATABASE_URL: jdbc:mysql://application-db:3306/applicationdb?allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      JDBC_DATABASE_PASSWORD: admin
      JDBC_DATABASE_USERNAME: admin
    ports:
      - 8080:8080
    networks:
      - game-network
      - application-network
      - authentication-network
      - session-network
    volumes:
      - maven_packages:/root/.m2
    container_name: application-service

networks: 
  game-network:
    name: game-network
  application-network:
    name: application-network
  session-network:
    name: session-network
  authentication-network:
    name: authentication-network

volumes:
  maven_packages:
    name: maven_packages