spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8080

auth:
  service:
    url: "http://localhost:8082"


game:
  service:
    url: "http://localhost:8081"
