spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/applicationdb?allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:administrator}
    dbcp2:
      max-wait-millis: 30000
      validation-query: SELECT 1
      validation-query-timeout: 30
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
server:
  port: 8080

auth:
  service:
    url: ${AUTHENTICATION_SERVICE_URL:http://localhost:8082}
    secret: "pluto"

game:
  service:
    url: ${GAME_SERVICE_URL:http://localhost:8081}
    secret: paperino

session:
  service:
    url: ${SESSION_SERVICE_URL:http://localhost:8084}
    secret: pippo
