spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8080

auth:
  service:
    url: "http://localhost:8082"


game:
  service:
    url: ${GAME_SERVICE_URL:http://localhost:8081}

session:
  service:
    url: ${SESSION_SERVICE_URL:http://localhost:8084}
